// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqbhyvnzpuezyqargqbn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xYmh5dm56cHVlenlxYXJncWJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM4ODQ5MDEsImV4cCI6MjA3OTQ2MDkwMX0.kd2qsxEMJZXnfAxAptQNV8U8u2ceyWUru8sO1moyPXo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});